---
# Load data
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'
  
# Install splunk
- name: Install software
  hosts: domain
  gather_facts: false
  tasks:
    - name: Install Splunk Forwarder
      win_chocolatey:
        name: splunk-universalforwarder
        state: present
